project:
  type: website

website:
  title: "Travis Green"
  navbar:
    right:
       - href: index.qmd
         text: Home
       - href: about.qmd
         text: About
       - href: research.html
         text: Research
       - href: project.html
         text: Project
       - href: CV.pdf
         text: CV
       - text: Assignments
         menu:
          - href: assignment1.html
            text: Assignment1
          - href: assignment02.html
            text: Assignment2
          - href: assignment03.html
            text: Assignment3
       
format: 
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

