---
title: "Assignment 1"
---

**Hypothesis:** The adoption of the agile mindset in municipal government operations leads to improved efficiency, increased responsiveness to community needs, and enhanced collaboration among departments, resulting in better overall performance and satisfaction with government services.

**Hypothesis 2:** The use of agile methodologies can enhance collaboration and communication among departments and stakeholders, leading to more efficient and effective decision-making and problem-solving.

Data collections would be through a survey of government employees from organizations such as The City of Austin and Miami-Dade, FL who have implemented the Agile methodolgy in their organization. This data can be compared to determine if there has been any improvement in performance and satisfaction.

Additional research could be through the ICMA Knowledge Network. The ICMA Knowledge Network provides articles, reports, and other resources on various topics related to local government management. ICMA has provided multiple articles on the use of the Agile mindset in local and county governments.

**Methods:** a combination of quantitative and qualitative research could be performed using an online survey with both Likert-scale responses and open text. The open text would provide an additional level of richness of the data based on free responses from the individuals.

The project would begin with permission from a city administrator to survey existing employees who have been involved with the Agile implementations. The use of the National Association of Public Administrators Agile Government would be used to provide introductions.
